# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  php_job:
    docker:
      # specify the version you desire here
      - image: php:7.1-apache
        environment:
          DEBUG: true
          DATABASE_URL: "mysql://root@127.0.0.1/AOU?encoding=utf8mb4&timezone=UTC&cacheMetadata=true"
          DATABASE_TEST_URL: "mysql://root@127.0.0.1/AOU?encoding=utf8mb4&timezone=UTC&cacheMetadata=true"
      - image: circleci/mysql:5.7
        command: mysqld  --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        environment:
          MYSQL_DATABASE: AOU
          MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: /var/www/html

    steps:
      - run: apt-get update && apt-get -y install git unzip zlib1g-dev libicu-dev
      - checkout
      - run: docker-php-ext-install pdo pdo_mysql zip intl
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
            php -r "copy('https://composer.github.io/installer.sig', 'composer-setup.sig');" && \
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('composer-setup.sig'))) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
            php composer-setup.php && \
            php -r "unlink('composer-setup.php');"
      - restore_cache:
          key: cakephp3-circleci-testci-{{ .Branch }}
      - run: php composer.phar install --dev --no-interaction
      - save_cache:
          key: cakephp3-circleci-testci-{{ .Branch }}
          paths:
            - "/home/ubuntu/.composer/cache"
      - run:
          name: create test repot dir
          command: mkdir -p $CIRCLE_TEST_REPORTS/phpunit
      - run:
          name: chmod permissions
          command: chmod +x bin/cake
      - run:
          name: Initialize Database
          command: bin/cake migrations migrate
      # run tests!
      - run: vendor/bin/phpunit

  vuex_job:
    docker:
      #- image: node:6
      - image: karthikiyengar/node-nightwatch:0.0.1
        environment:
          BABEL_ENV: development
    working_directory: ~/repo
    steps:
      - run: npm --v
      - checkout
      - restore_cache:
          key: cakephp3-circleci-testci-npm-cache-{{ .Branch }}
      - run: cd vuex && npm install
      - save_cache:
          key: cakephp3-circleci-testci-npm-cache-{{ .Branch }}
          paths:
            - "node_modules"
      - run: cd vuex && npm run lint
      
  eslint_javascript:
    docker:
      - image: node:6
    working_directory: /var/www/html
    steps:
      - run: npm --v
      - checkout
      - restore_cache:
          key: cakephp3-circleci-startuphub-npm-cache-{{ .Branch }}
      - run: npm install
      - save_cache:
          key: cakephp3-circleci-startuphub-npm-cache-{{ .Branch }}
          paths:
            - "/home/ubuntu/.npm-cache"
      - run: 
          name: Check Javascript source code by eslint
          command: node_modules/.bin/eslint webroot/js/common.js
      - run: 
          name: Check HTML source code by htmllint
          command: node_modules/.bin/htmllint webroot/html/*.html
workflows:
  version: 2
  build-all:
    jobs:
      - php_job
      #- vuex_job
      - eslint_javascript
